-- Enjoy this free quality of life product!
-- Make sure to join the Discord server for more!
-- https://discord.gg/invite/mECYYYtbx9

-- [! INSTRUCTIONS !]
-- 1: Publish the animation R6 Chatting Animation (Right Click > Save/Export > Save to Roblox) and copy the id.
-- 2: Paste your newly published animation id inside ChatAnimator module script > ChattingAnim.
-- 3: Place each folder inside their corresponding location.
-- 4: Ungroup each folder (CTRL + U).
-- 5: Make the most of ChatAnimator!

-- [ChatAnimator Module Q&A]
-- - When does the typing animation play on the player?
-- > The chatting animation plays whenever the player is focused on the chat input textbox.

-- - How can I use my own typing animation ID?
-- > Simple! Edit the AnimatonId below the ChatAnimator module script (ChattingAnim) to your own.

-- [Nebularno: My Contacts]
-- https://discord.com/users/1158168611974807583 or nebularno (Discord)
-- https://guns.lol/nebularno (Contacts)
-- https://nebularno.carrd.co (Portfolio)